hmcts/idam-user-profile-bridge

- build.gradle
Reverts hmcts/idam-user-profile-bridge#11
> Revert "Update plugin org.owasp.dependencycheck to v8.4.0"

- charts/idam-user-profile-bridge/Chart.yaml
- charts/idam-user-profile-bridge/values.yaml
https://tools.hmcts.net/jira/browse/SIDM-8836
Set ingressHost and envvars in helm chart.
```
[ ] Yes
[x] No
```
> Set values in helm chart 

- charts/idam-user-profile-bridge/Chart.yaml
- charts/idam-user-profile-bridge/values.yaml
Reverts hmcts/idam-user-profile-bridge#13
> Revert "Set values in helm chart "

- build.gradle
Reverts hmcts/idam-user-profile-bridge#14
> Revert "Revert "Update plugin org.owasp.dependencycheck to v8.4.0""

- charts/idam-user-profile-bridge/Chart.yaml
- charts/idam-user-profile-bridge/values.yaml
Reverts hmcts/idam-user-profile-bridge#15
> Revert "Revert "Set values in helm chart ""

- charts/idam-user-profile-bridge/Chart.yaml
- charts/idam-user-profile-bridge/values.yaml
- src/main/resources/logback-includes.xml
N/A
Get Vault to Mount
```
[ ] Yes
[X] No
```
> Get Vault to Mount

- Dockerfile
- build.gradle
N/A
upgrade app insights
```
[ ] Yes
[X] No
```
> other versions

- build.gradle
- charts/idam-user-profile-bridge/Chart.yaml
- charts/idam-user-profile-bridge/values.yaml
- config/owasp/suppressions.xml
- docker-compose.yml
- src/functionalTest/java/uk/gov/hmcts/idam/userprofilebridge/controllers/SpringFunctionalTest.java
- src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/jpa/StringListConverter.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/config/SchedulerConfig.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/error/ListenerErrorHandler.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/error/SchedulerErrorHandler.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/listeners/model/EventType.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventListener.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventPublisher.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/messaging/model/EventType.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/messaging/model/UserEvent.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/repository/InvitationEntityRepository.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/repository/model/InvitationEntity.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/repository/model/InvitationStatus.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/repository/model/InvitationType.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/InvitationService.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventService.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/UserProfileService.java
- src/main/resources/application.yaml
- src/smokeTest/java/uk/gov/hmcts/idam/userprofilebridge/controllers/SpringSmokeTest.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventListenerTest.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventPublisherTest.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/service/InvitationServiceTest.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventServiceTest.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/service/UserProfileServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-8836
Create events for accepted invitations
```
[ ] Yes
[X] No
```
> Create events for accepted invitations

- charts/idam-user-profile-bridge/Chart.yaml
- charts/idam-user-profile-bridge/values.aat.template.yaml
N/A
fix release name
```
[ ] Yes
[X] No
```
> fix release name

- build.gradle
- src/main/resources/application.yaml
N/A
remove caffeine
```
[ ] Yes
[X] No
```
> remove caffeine

- src/functionalTest/java/uk/gov/hmcts/idam/userprofilebridge/UserApiTest.java
- src/functionalTest/java/uk/gov/hmcts/idam/userprofilebridge/steps/ServiceProviderSteps.java
- src/functionalTest/java/uk/gov/hmcts/idam/userprofilebridge/steps/UserSteps.java
- src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/model/ServiceProvider.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/controllers/UserProfileController.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/controllers/UserProfileControllerTest.java
https://tools.hmcts.net/jira/browse/SIDM-8905
Add permissions
```
[ ] Yes
[X] No
```
> permissions

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- build.gradle
- charts/idam-user-profile-bridge/Chart.yaml
- charts/idam-user-profile-bridge/values.preview.template.yaml
- charts/idam-user-profile-bridge/values.yaml
- infrastructure/main.tf
- src/functionalTest/java/uk/gov/hmcts/idam/userprofilebridge/UserApiTest.java
- src/functionalTest/java/uk/gov/hmcts/idam/userprofilebridge/steps/BaseSteps.java
- src/functionalTest/java/uk/gov/hmcts/idam/userprofilebridge/steps/BridgeSteps.java
- src/functionalTest/java/uk/gov/hmcts/idam/userprofilebridge/steps/UserSteps.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/config/QueueConfig.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventListener.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventPublisher.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/repository/InvitationEntityRepository.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/InvitationService.java
- src/main/resources/application-disable-db.yaml
- src/main/resources/application-events-in-memory.yaml
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventListenerTest.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventPublisherTest.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/service/UserProfileServiceTest.java
Jira link (if applicable)
https://tools.hmcts.net/jira/browse/SIDM-8901
Change description
Use in memory events for PRs and add functional tests
> SIDM 8901 in memory events for PRs and add functional tests

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/properties/CategoryProperties.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventService.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-8909
categories from properties
> SIDM-8909 categories from properties

- build.gradle
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/idam/userprofilebridge/UserApiTest.java
- src/functionalTest/java/uk/gov/hmcts/idam/userprofilebridge/steps/BaseSteps.java
- src/functionalTest/java/uk/gov/hmcts/idam/userprofilebridge/steps/BridgeSteps.java
- src/functionalTest/java/uk/gov/hmcts/idam/userprofilebridge/steps/UserSteps.java
- src/main/java/uk/gov/hmcts/cft/idam/api/oidc/auth/PasswordGrantRequestInterceptor.java
- src/main/java/uk/gov/hmcts/cft/rpe/api/auth/RpeS2SRequestInterceptor.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SIDM-8901
add caseworker sync test
> SIDM-8901 add caseworker sync test

- .github/workflows/ci.yaml
- build.gradle
- lib/applicationinsights.json
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/controllers/UserProfileController.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/error/CommonExceptionHandler.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/error/ListenerErrorHandler.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventListener.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/InvitationService.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventService.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/UserProfileService.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/trace/TraceAttribute.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/util/PrincipalHelper.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/error/CommonExceptionHandlerTest.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/error/ListenerErrorHandlerTest.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/util/PrincipalHelperTest.java
> SIDM-8902 Error handling and logging

- charts/idam-user-profile-bridge/values.preview.template.yaml
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/config/QueueConfig.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/error/ListenerErrorHandler.java
> jms errors

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/error/ListenerErrorHandler.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventListener.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventService.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/UserProfileService.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/trace/TraceAttribute.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventListenerTest.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventServiceTest.java
Handle user profile and caseworker profile exceptions
> SIDM-8902 profile exceptions

- src/main/java/uk/gov/hmcts/idam/userprofilebridge/error/ListenerErrorHandler.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventListener.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventService.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/error/ListenerErrorHandlerTest.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventListenerTest.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventServiceTest.java
Move exception handling for listener into context of app insight operation
> SIDM-8902 move exception handling

- src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/error/SpringWebClientHelper.java
- src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/util/LogUtil.java
- src/main/java/uk/gov/hmcts/cft/idam/api/v2/common/util/ResponseUtil.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventListener.java
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/UserProfileService.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/service/UserProfileServiceTest.java
Check user and caseworker profiles exist before update
> SIDM-8902 Check user and caseworker profiles exist before update

- charts/idam-user-profile-bridge/Chart.yaml
- charts/idam-user-profile-bridge/values.preview.template.yaml
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/controllers/UserProfileController.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/controllers/UserProfileControllerTest.java
https://tools.hmcts.net/jira/browse/SIDM-8936
Switch to real s2s
> SIDM-8936 switch to real s2s

- src/main/java/uk/gov/hmcts/cft/rpe/api/auth/RpeS2SRequestInterceptor.java
https://tools.hmcts.net/jira/browse/SIDM-8936
Fix bearer
> SIDM-8936 fix bearer

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/SIDM-8936
Pipeline use different service id
> SIDM-8936 pipeline use different service id

- config/owasp/suppressions.xml
N/A
There is no fix released yet for CVE-2023-36052. This is a vulnerability in azure-cli so might not be related to the azure libs we are using. 
Tidy up suppressions.xml.
> Suppress CVE-2023-36052 

- src/main/java/uk/gov/hmcts/idam/userprofilebridge/config/QueueConfig.java
Reverts hmcts/idam-user-profile-bridge#208
> Revert "SIDM-9136 durable subscription"

- .gitignore
- src/main/java/uk/gov/hmcts/idam/userprofilebridge/config/QueueConfig.java
https://tools.hmcts.net/jira/browse/SIDM-9136
Catch errors and set subscription shared durable
> SIDM-9136 catch jms errors

- src/main/resources/logback-includes.xml
https://tools.hmcts.net/jira/browse/SIDM-9153
Change log levels
> change jms log level

- src/main/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventPublisher.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/messaging/UserEventPublisherTest.java
https://tools.hmcts.net/jira/browse/SIDM-9152
Catch publish exceptions
> SIDM-9152 catch publish exceptions

- config/owasp/suppressions.xml
N/A
Try out removing some CVEs.
> Remove unnecessary CVE suppressions

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SIDM-9184
Remove null attributes in json responses
> exclude nulls

- build.gradle
Spring boot also has selenium which clashes with serentiy
> Fix serenity

- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventService.java
N/A
use enum set for natural ordering
> Use enum set for natural ordering

- src/main/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventService.java
- src/test/java/uk/gov/hmcts/idam/userprofilebridge/service/UserEventServiceTest.java
https://tools.hmcts.net/jira/browse/SIDM-9222
Add flag to enable/disable caseworker api sync calls
> SIDM-9222 caseworker api flag

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SIDM-9233
Add pooling to prevent MessageProducer idle timeouts
> SIDM-9123 Add pooling to prevent MessageProducer idle timeouts

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SIDM-9286
Suppress https://github.com/advisories/GHSA-m5vv-6r4h-3vj9 as there is no upgrade path currently (+ the version in use is excluded in NVD's report - maybe it will get fixed in the dependencycheck plugin?)
> SIDM-9286: Suppress CVE-2024-35255

- charts/idam-user-profile-bridge/Chart.yaml
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
> HELM OCI IDAM - idam-user-profile-bridge/Chart.yaml

- Jenkinsfile_nightly
- build.gradle
- config/fortify-client.properties
https://tools.hmcts.net/jira/browse/SIDM-9754
Add fortify
N/A
> SIDM-9754 add fortify

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SIDM-9790
Update versions
Yes
> SIDM-9790 Update versions
